config/routes.rb
Rails.application.routes.draw do

  devise_for :staff_members

  root 'tickets#index'
  resources :tickets, except: [:destroy] do
    resources :ticket_versions, only: [:index]
  end
  get '/tickets/retrieve/:status_code' => 'tickets#index', as: :tickets_retrieve

  post '/search' => 'search_tickets#search', as: :search

end

app/models/staff_member.rb
class StaffMember < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true
end

app/models/status.rb
class Status < ActiveRecord::Base

  DEFAULT = :waiting_for_staff

  CODES = [DEFAULT, :waiting_for_customer, :on_hold,
                    :canceled, :completed]

  scope :active, -> { where(active: true) }

  CODES.each do |code|
    define_singleton_method(code) do
      find_by(code: code)
    end
  end

  def self.active_values
    self.active.map { |status| [status.name, status.id] }
  end

  def self.check(status)
    return false if status.blank?
    CODES.include?(status.to_sym)
  end

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  include TicketReferenceGenerator

  self.primary_key = 'id'

  validates :subject, :name, :body, :status, :departure, presence: true
  validates :subject, length: { minimum: 3,  maximum: 50 }
  validates :body, length: { minimum: 1, maximum: 250 }
  validates :staff_comment, length: { maximum: 250 }
  validates :email, :name, presence: true
  validates :email, email: true

  before_create :set_ticket_id
  before_validation :set_default_status
  after_create :send_created_email
  after_save :send_updated_email

  belongs_to :status
  belongs_to :staff_member
  attr_accessor :customer_mode

  #Versions
  has_paper_trail(if: Proc.new { |t| t.can_save_new_version? })

  #SOLR
  searchable do
    text :id, :name, :subject, :body, :staff_comment, :departure
  end

  #Scopes by statuses
  Status.active.each{|status|
    scope status.code, -> {
      where(status: status)
    }
  }

  def self.search_by_phrase(phrase)
    Ticket.search { fulltext "#{phrase}" }.results
  end

  def self.retrieve(status_code)
    send(Status.check(status_code) ? status_code : Status::DEFAULT)
  end

  def can_save_new_version?
    self.status_id_changed? || self.staff_member_id_changed? || self.staff_comment_changed?
  end

  private
  def set_default_status
    self.status = Status.waiting_for_staff if status.blank? || customer_mode
  end

  def set_ticket_id
    begin
      self.id = generate_reference
    end while Ticket.exists?(:id => id)
  end

  def send_created_email
    TicketMailer.create(self).deliver_later
  end

  def send_updated_email
    TicketMailer.update(self).deliver_later if can_save_new_version?
  end

end

app/models/ticket_reference_generator.rb
require 'securerandom'

module TicketReferenceGenerator

  def generate_reference
    Array.new(3) { letters_str(3) }.join("-#{hex_str}-")
  end

  def letters_str(number)
    [*('A'..'Z')].sample(number).join
  end

  def hex_str
    SecureRandom.hex
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def user_for_paper_trail
    staff_member_signed_in? ? current_staff_member.email : 'customer'
  end

  def info_for_paper_trail
    { ip: request.remote_ip }
  end
end

app/controllers/search_tickets_controller.rb
class SearchTicketsController < ApplicationController

  before_action :authenticate_staff_member!

  def search
    @phrase = search_params[:phrase]
    @tickets = Ticket.search_by_phrase(@phrase)
    render 'tickets/index'
  end

  private
  def search_params
    params.require(:search).permit([:phrase])
  end

end

app/controllers/ticket_versions_controller.rb
class TicketVersionsController < ApplicationController
  before_action :set_ticket

  def index
    @versions = @ticket.versions
  end

  private
    def set_ticket
      @ticket = Ticket.find(params[:ticket_id])
    end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :previous, :next, :edit, :update, :destroy]

  respond_to :html

  def index
    return redirect_to new_ticket_path unless staff_member_signed_in?
    @tickets = Ticket.retrieve(params[:status_code])
  end

  def show
  end

  def new
    @ticket = Ticket.new
  end

  def edit
  end

  def create
    @ticket = Ticket.new(ticket_params)
    redirect_to(@ticket, notice: 'Ticket was successfully created.') and return if @ticket.save
    render :new
  end

  def update
    redirect_to(@ticket, notice: 'Ticket was successfully updated.') and return if @ticket.update_attributes(ticket_params)
    render :edit
  end

  private
    def set_ticket
      @ticket = Ticket.find(params[:id])
      @ticket.customer_mode = !staff_member_signed_in?
    end

    def permitted_params
      params = [:name, :email, :departure, :subject, :body]
      params.concat [:status_id, :staff_member_id, :staff_comment] if staff_member_signed_in?
      params
    end

    def ticket_params
      params.require(:ticket).permit(permitted_params)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "XTickPro"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"

  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand(href="/") XTickPro
        .navbar-collapse.collapse
          %ul.nav.nav-pills.pull-right
            - if staff_member_signed_in?
              %li= link_to 'Sign out', destroy_staff_member_session_path, method: :delete
            - else
              %li= link_to 'Sign in', new_staff_member_session_path


    .container
      .row
        .col-lg-12
          = bootstrap_flash
          - if staff_member_signed_in?
            = render 'search_tickets/search'
          = yield

      %footer
        %p &copy; Test Company 2015

app/views/search_tickets/_search.html.haml
=bootstrap_form_for 'search', as: :post, url: search_path, layout: :inline do |f|
  = f.text_field :phrase, hide_label: true, placeholder: 'Enter your search...', value: @phrase.nil? ? '' :@phrase
  = f.submit 'Search'

app/views/ticket_versions/index.html.haml
.page-header
  %h1=t('ticket.history_index')

%p
  ="Ticket id: #{@ticket.id}"

%p
  = link_to t('ticket.new'), new_ticket_path
  \|
  = link_to t('ticket.edit'), edit_ticket_path(@ticket)
  \|
  = link_to t('ticket.back'), tickets_path

- if @versions.blank?
  %p
    = t('ticket.no_history')
- else
  %table.table.table-striped
    %thead
      %tr
        %th
          =t('ticket.table.name')
        %th
          =t('ticket.table.email')
        %th
          =t('ticket.table.departure')
        %th
          =t('ticket.table.subject')
        %th
          =t('ticket.table.body')
        %th
          =t('ticket.table.status')
        %th
          =t('ticket.history_table.event')
        %th
          =t('ticket.history_table.modified_by')
        %th
          =t('ticket.history_table.modified_at')
        %th
          =t('ticket.history_table.ip')
        %th
          =t('ticket.table.owner')
        %th
          =t('ticket.table.comment')
    %tbody
      - @versions.each do |version|
        - ticket = version.reify
        - ticket ||= @ticket
        %tr
          %td= ticket.name
          %td= ticket.email
          %td= ticket.departure
          %td= ticket.subject
          %td= ticket.body
          %td= ticket.status.name
          %td= version.event
          %td= version.whodunnit
          %td= version.created_at
          %td= version.ip
          %td= ticket.staff_member.try(:name)
          %td= ticket.staff_comment

app/views/tickets/_form.html.haml
=bootstrap_form_for @ticket do |f|
  = f.text_field :name
  = f.email_field :email
  = f.text_field :departure
  = f.text_field :subject
  = f.text_area :body
  - if staff_member_signed_in?
    = f.select(:status_id, Status.active_values)
    = f.select(:staff_member_id, StaffMember.all.map {|sm| [sm.name, sm.id]})
    = f.text_area :staff_comment
  = f.submit t('ticket.save')

app/views/tickets/edit.html.haml
.page-header
  %h1=t('ticket.edit')

= link_to t('ticket.show'), @ticket
\|
= link_to t('ticket.back'), tickets_path

= render 'form'

app/views/tickets/index.html.haml
.page-header
  %h1=t('ticket.index')

- if staff_member_signed_in?
  %p
    %ul.nav.nav-pills
      - Status.active.each do |status|
        %li= link_to status.name, tickets_retrieve_path(status.code)

= link_to t('ticket.new'), new_ticket_path
%div
  - if @tickets.blank?
    %p
      = t('ticket.not_found')
  - else
    %table.table.table-striped
      %thead
        %tr
          %th
            =t('ticket.table.name')
          %th
            =t('ticket.table.email')
          %th
            =t('ticket.table.departure')
          %th
            =t('ticket.table.subject')
          %th
            =t('ticket.table.body')
          %th
            =t('ticket.table.status')
          %th
            =t('ticket.table.owner')
          %th
          %th
          %th

      %tbody
        - @tickets.each do |ticket|
          %tr
            %td= ticket.name
            %td= ticket.email
            %td= ticket.departure
            %td= ticket.subject
            %td= ticket.body
            %td= ticket.status.name
            %td= ticket.staff_member.try(:name)
            %td= link_to t('ticket.show'), ticket
            %td= link_to t('ticket.edit'), edit_ticket_path(ticket)
            %td= link_to t('ticket.history'), ticket_ticket_versions_path(ticket)

app/views/tickets/new.html.haml
.page-header
  %h1=t('ticket.new')

= link_to t('ticket.back'), tickets_path

= render 'form'

app/views/tickets/show.html.haml
.page-header
  %h1
    =t('ticket.show')
%p
  %b
    ="#{t('ticket.table.id')}:"
  =@ticket.id
%p
  %b
    ="#{t('ticket.table.name')}:"
  =@ticket.name
%p
  %b
    ="#{t('ticket.table.email')}:"
  =@ticket.email
%p
  %b
    ="#{t('ticket.table.departure')}:"
  =@ticket.departure
%p
  %b
    ="#{t('ticket.table.subject')}:"
  =@ticket.subject
%p
  %b
    ="#{t('ticket.table.body')}:"
  =@ticket.body
%p
  %b
    ="#{t('ticket.table.status')}:"
  =@ticket.status.name
%p
  %b
    ="#{t('ticket.table.comment')}: #{@ticket.staff_comment.blank? ? t('ticket.table.no_comment') : @ticket.staff_comment}"


= link_to t('ticket.history'), ticket_ticket_versions_path(@ticket)
\|
= link_to t('ticket.edit'), edit_ticket_path(@ticket)
\|
= link_to t('ticket.back'), tickets_path